{"uuid": "162d68ce-f5b2-4485-b1eb-67a2a7c34801", "children": ["17fbe67a-beb2-4eba-a95f-5ccff5804d9d", "7787f8ec-10d3-44c7-8e0a-78396cb0854c", "f8d19b3b-dc00-4299-92d6-4dd09678609c"], "befores": [{"name": "my_set2_class", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"name\",\"selector\":\"phone\"}\n  (Session info: chrome=80.0.3987.149)\n  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"F:\\PycharmProjects\\python13-web\\class12_z_fixture\\conftest.py\", line 41, in my_set2_class\n    login_page.submit_userinfo(\n  File \"F:\\PycharmProjects\\python13-web\\class12_z_fixture\\pages\\login_page.py\", line 27, in submit_userinfo\n    phone_ele = self.driver.find_element_by_name('phone')\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 496, in find_element_by_name\n    return self.find_element(by=By.NAME, value=name)\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 976, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\zhouchao\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1585820760338, "stop": 1585820772877}], "start": 1585820760338, "stop": 1585820775235}